<?php

/** @var \Magento\Catalog\Block\Product\Gallery $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

    $width = $block->getImageWidth();
$imageUrl = $block->getImageUrl();
?>

<!--<img class="product-main-image" src="https://images.unsplash.com/photo-1575936123452-b67c3203c357?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80" alt="image"/>-->
<div>
    <h2>
        <?=$width?>
    </h2><h2>
        <?=$block->getImageUrl() ? $block->getImageUrl() : 'No Image' ?>
    </h2>
    <h2>dasdasd</h2>
</div>
