<?php
    /**
    * @var  Gal\Gwd\Block\Review $block
     *
     */
    $reviews = $block->getProductReviews();


?>

<div class="myshop-reviews">

    <?php if ($reviews->getSize() > 0) : ?>
            <h2 class="myshop-reviews__title">Product Reviews</h2>
            <ul class="myshop-reviews__list">
                <?php foreach ($reviews as $review) : ?>
                    <li class="myshop-reviews__item">
                        <h3 class="myshop-reviews__item-title"><?= $review->getTitle() ?></h3>
                        <p class="myshop-reviews__item-body"><?= $review->getDetail() ?></p>
                    </li>
                <?php endforeach; ?>
            </ul>
    <?php endif; ?>

</div>

